import type {
  Product,
  Order,
  Invoice,
  Customer,
  BusinessInfo,
} from "./types";

// ─── Company Info ────────────────────────────────────────────────────────────

export const COMPANY_INFO: BusinessInfo = {
  name: "Interia s.r.o.",
  ico: "12345678",
  dic: "2012345678",
  icdph: "SK2012345678",
  address: {
    street: "Priemyselná 1",
    city: "Bratislava",
    zip: "821 09",
    country: "Slovensko",
  },
  bank: "Slovenská sporiteľňa",
  iban: "SK00 0900 0000 0012 3456 7890",
  swift: "GIBASKBX",
  email: "info@interia.sk",
  phone: "+421 900 000 000",
  web: "https://interia.sk",
};

// ─── Products ────────────────────────────────────────────────────────────────

export const PRODUCTS: Product[] = [
  // --- Materiály ---
  {
    id: "mat-001",
    sku: "MAT-PLECH-2MM",
    name: "Oceľový plech 2 mm",
    description:
      "Valcovaný oceľový plech hrúbky 2 mm, vhodný pre lisovanie, zváranie a ďalšie opracovanie. Formát 1 000 × 2 000 mm.",
    category: "materialy",
    price: 28.5,
    vatRate: 0.2,
    unit: "ks",
    stock: 150,
    minOrderQuantity: 1,
    images: ["/images/products/plech-2mm.jpg"],
    attributes: [
      { name: "Hrúbka", value: "2", unit: "mm" },
      { name: "Formát", value: "1000×2000", unit: "mm" },
      { name: "Materiál", value: "S235JR" },
    ],
    tags: ["plech", "oceľ", "materiál"],
    isActive: true,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "mat-002",
    sku: "MAT-PLECH-3MM",
    name: "Oceľový plech 3 mm",
    description:
      "Valcovaný oceľový plech hrúbky 3 mm. Formát 1 000 × 2 000 mm.",
    category: "materialy",
    price: 42.0,
    vatRate: 0.2,
    unit: "ks",
    stock: 120,
    minOrderQuantity: 1,
    images: ["/images/products/plech-3mm.jpg"],
    attributes: [
      { name: "Hrúbka", value: "3", unit: "mm" },
      { name: "Formát", value: "1000×2000", unit: "mm" },
      { name: "Materiál", value: "S235JR" },
    ],
    tags: ["plech", "oceľ", "materiál"],
    isActive: true,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "mat-003",
    sku: "MAT-PROFIL-50X50",
    name: "Uzavretý profil 50×50×3 mm",
    description:
      "Štvorhranny uzavretý oceľový profil 50×50 mm, hrúbka steny 3 mm. Dĺžka 6 m.",
    category: "materialy",
    price: 35.0,
    vatRate: 0.2,
    unit: "ks",
    stock: 200,
    minOrderQuantity: 1,
    images: ["/images/products/profil-50x50.jpg"],
    attributes: [
      { name: "Rozmery", value: "50×50", unit: "mm" },
      { name: "Hrúbka steny", value: "3", unit: "mm" },
      { name: "Dĺžka", value: "6", unit: "m" },
      { name: "Materiál", value: "S235JR" },
    ],
    tags: ["profil", "oceľ", "konštrukčný materiál"],
    isActive: true,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "mat-004",
    sku: "MAT-NEREZ-1.5MM",
    name: "Nerezový plech 1.5 mm",
    description:
      "Nerezový plech hrúbky 1,5 mm, povrch 2B. Formát 1 000 × 2 000 mm. Vhodný pre potravinársky priemysel.",
    category: "materialy",
    price: 89.0,
    vatRate: 0.2,
    unit: "ks",
    stock: 60,
    minOrderQuantity: 1,
    images: ["/images/products/nerez-1.5mm.jpg"],
    attributes: [
      { name: "Hrúbka", value: "1.5", unit: "mm" },
      { name: "Formát", value: "1000×2000", unit: "mm" },
      { name: "Materiál", value: "AISI 304" },
      { name: "Povrch", value: "2B" },
    ],
    tags: ["nerez", "plech", "potravinársky"],
    isActive: true,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  // --- Polotovary ---
  {
    id: "pol-001",
    sku: "POL-KONZOLA-A",
    name: "Konzola typ A – zváraná",
    description:
      "Štandardná oceľová konzola zváraná z plechu S235, povrchovo upravená – základný náter. Nosnosť 150 kg.",
    category: "polotovary",
    price: 12.5,
    vatRate: 0.2,
    unit: "ks",
    stock: 500,
    minOrderQuantity: 10,
    images: ["/images/products/konzola-a.jpg"],
    attributes: [
      { name: "Nosnosť", value: "150", unit: "kg" },
      { name: "Materiál", value: "S235" },
      { name: "Povrch", value: "základný náter" },
    ],
    tags: ["konzola", "polotovar", "zváraný diel"],
    isActive: true,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "pol-002",
    sku: "POL-RAM-OKNO",
    name: "Rám okna – polotovar",
    description:
      "Zváraný oceľový rám pre priemyselné okná. Rozmery 600×800 mm. Dodávané bez zasklenia.",
    category: "polotovary",
    price: 48.0,
    vatRate: 0.2,
    unit: "ks",
    stock: 80,
    minOrderQuantity: 5,
    images: ["/images/products/ram-okno.jpg"],
    attributes: [
      { name: "Rozmery", value: "600×800", unit: "mm" },
      { name: "Materiál", value: "S235" },
    ],
    tags: ["rám", "okno", "polotovar"],
    isActive: true,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "pol-003",
    sku: "POL-STUPACKA",
    name: "Stupačka – zváraná",
    description:
      "Oceľová stupačka pre priemyselné rebríky a schody. Dĺžka 300 mm, pozinkovaná.",
    category: "polotovary",
    price: 5.9,
    vatRate: 0.2,
    unit: "ks",
    stock: 1000,
    minOrderQuantity: 50,
    images: ["/images/products/stupacka.jpg"],
    attributes: [
      { name: "Dĺžka", value: "300", unit: "mm" },
      { name: "Povrch", value: "pozink" },
    ],
    tags: ["stupačka", "rebrík", "polotovar"],
    isActive: true,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  // --- Atypická výroba ---
  {
    id: "aty-001",
    sku: "ATY-OCELOVAKONSTRUKCIA",
    name: "Atypická oceľová konštrukcia – na mieru",
    description:
      "Kompletná výroba atypickej oceľovej konštrukcie podľa dodaných výkresov alebo požiadaviek zákazníka. Cena závisí od rozsahu zákazky – kontaktujte nás pre cenovú ponuku.",
    category: "atypicka-vyroba",
    price: 0,
    vatRate: 0.2,
    unit: "projekt",
    stock: 99,
    minOrderQuantity: 1,
    images: ["/images/products/atypicka-konstrukcia.jpg"],
    attributes: [
      { name: "Výroba", value: "na mieru" },
      { name: "Materiál", value: "podľa požiadavky" },
      { name: "Povrch", value: "podľa požiadavky" },
    ],
    tags: ["atypická výroba", "na mieru", "konštrukcia"],
    isActive: true,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "aty-002",
    sku: "ATY-LASEROVY-REZ",
    name: "Laserové rezanie – na mieru",
    description:
      "Laserové rezanie plechov podľa DXF/DWG súborov zákazníka. Tolerancie ±0,1 mm. Materiály: oceľ, nerez, hliník. Cena podľa množstva a zložitosti.",
    category: "atypicka-vyroba",
    price: 0,
    vatRate: 0.2,
    unit: "projekt",
    stock: 99,
    minOrderQuantity: 1,
    images: ["/images/products/laser-rez.jpg"],
    attributes: [
      { name: "Tolerancia", value: "±0.1", unit: "mm" },
      { name: "Max. hrúbka (oceľ)", value: "20", unit: "mm" },
      { name: "Max. hrúbka (nerez)", value: "12", unit: "mm" },
      { name: "Max. hrúbka (hliník)", value: "15", unit: "mm" },
    ],
    tags: ["laser", "rezanie", "atypická výroba"],
    isActive: true,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "aty-003",
    sku: "ATY-OHYBANIE",
    name: "Ohýbanie plechov – na mieru",
    description:
      "CNC ohýbanie plechov podľa výkresovej dokumentácie zákazníka. Max. dĺžka ohybu 3 000 mm. Tolerancie ±0,5°.",
    category: "atypicka-vyroba",
    price: 0,
    vatRate: 0.2,
    unit: "projekt",
    stock: 99,
    minOrderQuantity: 1,
    images: ["/images/products/ohybanie.jpg"],
    attributes: [
      { name: "Max. dĺžka ohybu", value: "3000", unit: "mm" },
      { name: "Tolerancia uhla", value: "±0.5", unit: "°" },
    ],
    tags: ["ohýbanie", "CNC", "atypická výroba"],
    isActive: true,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
];

// ─── Sample Customers ─────────────────────────────────────────────────────────

export const SAMPLE_CUSTOMERS: Customer[] = [
  {
    id: "cust-001",
    name: "Stavby a.s.",
    email: "objednavky@stavby.sk",
    phone: "+421 901 111 222",
    ico: "11223344",
    dic: "2011223344",
    icdph: "SK2011223344",
    address: {
      street: "Továrenská 5",
      city: "Bratislava",
      zip: "821 04",
      country: "Slovensko",
    },
    isCompany: true,
  },
];

// ─── Sample Orders ────────────────────────────────────────────────────────────

export const SAMPLE_ORDERS: Order[] = [
  {
    id: "ord-001",
    orderNumber: "2024-001",
    status: "dorucena",
    customer: SAMPLE_CUSTOMERS[0],
    items: [
      {
        productId: "mat-001",
        productName: "Oceľový plech 2 mm",
        sku: "MAT-PLECH-2MM",
        quantity: 20,
        unitPrice: 28.5,
        vatRate: 0.2,
        unit: "ks",
      },
      {
        productId: "pol-001",
        productName: "Konzola typ A – zváraná",
        sku: "POL-KONZOLA-A",
        quantity: 100,
        unitPrice: 12.5,
        vatRate: 0.2,
        unit: "ks",
      },
    ],
    shippingAddress: SAMPLE_CUSTOMERS[0].address,
    billingAddress: SAMPLE_CUSTOMERS[0].address,
    createdAt: "2024-03-15T09:00:00Z",
    updatedAt: "2024-03-20T14:00:00Z",
  },
];

// ─── Sample Invoices ──────────────────────────────────────────────────────────

export const SAMPLE_INVOICES: Invoice[] = [
  {
    id: "inv-001",
    invoiceNumber: "FA-2024-001",
    status: "paid",
    orderId: "ord-001",
    supplier: COMPANY_INFO,
    customer: SAMPLE_CUSTOMERS[0],
    items: [
      {
        description: "Oceľový plech 2 mm (MAT-PLECH-2MM)",
        quantity: 20,
        unit: "ks",
        unitPrice: 28.5,
        vatRate: 0.2,
      },
      {
        description: "Konzola typ A – zváraná (POL-KONZOLA-A)",
        quantity: 100,
        unit: "ks",
        unitPrice: 12.5,
        vatRate: 0.2,
      },
    ],
    issueDate: "2024-03-15",
    dueDate: "2024-03-29",
    paymentMethod: "transfer",
    variableSymbol: "2024001",
    note: "Ďakujeme za Vašu objednávku.",
    createdAt: "2024-03-15T09:30:00Z",
    updatedAt: "2024-03-29T11:00:00Z",
  },
  {
    id: "inv-002",
    invoiceNumber: "FA-2024-002",
    status: "issued",
    supplier: COMPANY_INFO,
    customer: SAMPLE_CUSTOMERS[0],
    items: [
      {
        description: "Laserové rezanie – na mieru (ATY-LASEROVY-REZ)",
        quantity: 1,
        unit: "projekt",
        unitPrice: 350.0,
        vatRate: 0.2,
      },
    ],
    issueDate: "2024-04-01",
    dueDate: "2024-04-15",
    paymentMethod: "transfer",
    variableSymbol: "2024002",
    createdAt: "2024-04-01T08:00:00Z",
    updatedAt: "2024-04-01T08:00:00Z",
  },
];
